app_tk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('form/', include('modelraihan.urls')),
    path('berita/', include('berita.urls')),
    path('feedback', include('feedback.urls')),
    path('edukasi/', include('home.urls')),
    path('tanya/', include('home.urls')),
    path('admintanya/', include('home.urls')),
]

if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, 
                              document_root=settings.MEDIA_ROOT) 

berita/urls.py
from django.urls import path
from . import views
from .views import AddBeritaView, BeritaView, BeritaDetailView
from django.views.decorators.csrf import csrf_exempt

app_name = 'berita'

urlpatterns = [
    path('upload', AddBeritaView.as_view(), name='upload'),
    path('', BeritaView.as_view(), name='list'),
    path('detail/<int:pk>', BeritaDetailView.as_view(), name='detail'),
    path("cari", csrf_exempt(views.cari), name="cari"),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('edukasi/', views.edukasi, name='edukasi'),
    path('tanya/', views.tanya, name='tanya'),
    path('contacts', views.contacts, name='contacts'),
    path('admintanya/', views.admintanya, name='admintanya')
]

berita/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Berita(models.Model):
    title = models.CharField(max_length=500, blank=True)
    description = models.TextField(max_length=5000, blank=True)
    document = models.ImageField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('berita:list')

berita/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, CreateView
from .models import Berita
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core import serializers
import json
from django.http import HttpResponse
from django.http import JsonResponse

# Create your views here.
@method_decorator(login_required(login_url='login'), name='dispatch')
class AddBeritaView(CreateView):
    model = Berita
    template_name = 'upload_berita.html'
    fields = '__all__'

class BeritaView(ListView):
    model = Berita
    template_name = 'list_berita.html'
    context_object_name = 'berita'
    paginate_by = 4
    queryset = Berita.objects.all()

class BeritaDetailView(DetailView):
    model = Berita
    template_name = 'detail_berita.html'

def cari(request):
    if request.method == "POST":
        search_str = json.loads(request.body).get('searchText')
        beritas = Berita.objects.filter(title__icontains=search_str) | Berita.objects.filter(uploaded_at__istartswith=search_str)
        data = beritas.values()
        return JsonResponse(list(data), safe=False)

berita/templates/detail_berita.html
{% extends 'base.html' %}

{% block meta %}
    <title>{{ berita.title }}</title>
    <style>
        .switch {
            height: 150px;
            width: 90%;
            margin: 20px;
        }

        .button-toggle-wrap {
            float: right;
            text-align: center;
        }

        .button-toggle {
            display: inline-block;
            background: #bbbbbb;
            border-radius: 3px;
            height: 48px;
            padding: 4px;
            width: 101px;
            position: relative;
            box-shadow: inset 0 1px 3px rgba(0, 0, 0, 0.22);
        }
        .button-toggle .handle {
            position: absolute;
            left: 4px;
            right: auto;
            width: 40px;
            height: 40px;
            background: #fff;
            border-radius: 3px;
            transition: all 0.4s cubic-bezier(0.33, 1.6, 0.66, 1);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.22);
        }

        .toggler {
            display: none;
        }
        .toggler:checked + .button-toggle {
            background: #f07464;
        }
        .toggler:checked + .button-toggle .handle {
            left: 57px;
        }
    </style>
{% endblock meta %}

{% block content %}
<div class="switch">
    <label class="button-toggle-wrap">
        <p class="my-text">Light mode</p>
        <input class="toggler" type="checkbox" data-toggle="button-toggle"/>
        <div class="button-toggle">
            <div class="handle">
                <div class="bars"></div>
            </div>
        </div>
    </label>
</div>

<div class="detail-berita">
    <h1>{{ berita.title }}</h1>
    <p>{{ berita.uploaded_at }}</p>
    <img src="/media/{{ berita.document }}">
    <pre>{{ berita.description }}</pre>
    <a style="text-decoration:none;" href="/berita/">
        <div class="back-tag">
            <p>Kembali</p>
        </div>
    </a>
</div>
<script type="text/javascript">
$(function() {
	$("[data-toggle]").click(function() {
		var target = $(".my-text");
		if($(this).prop('checked')) {
            target.html('Dark mode');
            $("body").css("color", "#ffffff");
            $('body').css("background-color", '#242424');
            $("pre").css("color", "#ffffff");
            $('pre').css("background-color", '#242424');
		} else {
            target.html('Light mode');
            $("body").css("color", "#000000");
            $('body').css("background-color", '#ffffff');
            $("pre").css("color", "#000000");
            $('pre').css("background-color", '#ffffff');
            
		}
	})
})
</script>
{% endblock content %}

berita/templates/list_berita.html
{% extends 'base.html' %}

{% block meta %}
    <title>Berita Terkini COVID-19</title>
{% endblock meta %}

{% block content %}
<div class="jumbotron">
    <div class="container" id="jumbocontent">
    <h1 class="display-4"><b>Berita Terkini</b></h1>
    <p class="lead"> Berita terkini COVID-19 di Indonesia </p>
    <hr class="my-4">
    </div>
</div>
<div class="search-berita">
    <h1>Cari Berita</h1>
    <input id="keyword" type="search" placeholder="Masukkan kata kunci">
    <ol id="hasil">
    </ol>
</div>

<div class="list-berita">
    <div class="row" id="cobahasil">
        {% for berita in object_list %}
        <div class="col-lg-6 col-md-12">
            <div class="berita">
                <a href="{% url 'berita:detail' berita.pk  %}">
                    <img src="../media/{{ berita.document }}"><br/>
                    <p>{{ berita.uploaded_at }}<br/></p>
                    <h2>{{ berita.title }}</h2>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>

        {% if is_paginated %}
        <div style="clear: both;"></div>
        <div class="page">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }}</span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        </div>
        {% endif %}
</div>

<script type="text/javascript">

    $("#keyword").keydown(function() {
        $(this).css("background-color", '#ff6969');
    })

    $("#keyword").keyup(function () {
        $(this).css("background-color", '#ffffff');
        var isi_keyword = $("#keyword").val();
        console.log(isi_keyword);
        cari(isi_keyword)
    })

    function cari(data) {
        $.ajax({
            async: true,
            url: "cari",
            data: JSON.stringify({ searchText: data }),
            type: "POST",
            success: function (hasil) {
                console.log(hasil);
                var obj_hasil = $("#cobahasil");
                obj_hasil.empty();
                for (i = 0; i < hasil.length; i++) {
                    var tmp_title = hasil[i].title;
                    var tmp_date = hasil[i].uploaded_at;
                    var tmp_img = hasil[i].document;
                    var tmp_id = hasil[i].id;
                    console.log(tmp_title);
                    obj_hasil.append(
                        '<div class="col-lg-6 col-md-12">' +
                            '<div class="berita">' +
                                '<a href="detail/' + tmp_id + '">' +
                                    '<img src="../media/' + tmp_img + '"><br/>' +
                                    '<p>' + tmp_date + '<br/></p>' +
                                    '<h2>' + tmp_title + '</h2>' +
                                '</a>' +
                            '</div>' +
                        '</div>'
                    );
                }
            }
        })
    }
</script>
{% endblock content %}

berita/templates/upload_berita.html
{% extends 'base.html' %}

{% block meta %}
    <title>Upload Berita</title>
{% endblock meta %}

{% block content %}
{% if user.is_authenticated %}
    <div class="upload-berita" id="upload">
        <h1>Tambah Berita</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Upload</button>
        </form>
    </div>
{% endif %}

{% if not user.is_authenticated %}
<div style="font-family: Quicksand;" class="justify-content-center flex align-items-center mt-5">

    <div class="flex flex-column"style="text-align: center;">
        <h1>
            Silahkan Login terlebih dahulu
        </h1>
        <div class="flex flex-row justify-content-around" style="text-align: center;">
          <button type="button" class="btn btn-outline-dark"><a href="/form/login">Login</a></button>
        </div>

    </div>
</div>
{% endif %}
<script type="text/javascript">
    $(document).ready(function(){
        $("#upload").mouseenter(function(){
            $(this).css("background-color", '#ff6969');
        });
        $("#upload").mouseleave(function(){
            $(this).css("background-color", '#fafbfc');
        });
    });
</script>
{% endblock content %}